services:
  database:
    container_name: database_container
    image: postgres:latest
    restart: always
    ports: ["5432:5432"]
    environment:
      POSTGRES_USER: man
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: db
    
  deno:
    container_name: backend_container
    build:
      context: docker/backend
    restart: always
    working_dir: /var/www/application
    volumes: [./:/var/www/application]
    ports: ["8080:8080"]
    links:
      - database

  shell:
    container_name: shell_container
    build:
      context: docker/shell
    working_dir: /var/www/application
    tty: true
    links:
      - database
    volumes:
      - ./:/var/www/application